#BASE IMAGE
FROM node:20.9.0-alpine
#SETTING THE WORKING DIRECTORY
WORKDIR /todoapp
#COPYING ALL THE FILES
COPY . .
#INSTALLING EVERY DEPEDENCIES
RUN npm install
#EXPOSING THE LISTENING PORT
EXPOSE 3000
#RUNNING THE APP
CMD  [ "node", "app.js" ]